# Generated by Django 5.0.2 on 2024-10-18 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('level', models.IntegerField()),
                ('specialization', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=10)),
            ],
        ),
    ]
