# Generated by Django 5.0.2 on 2024-10-18 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='email',
            field=models.EmailField(default='default@example.com', max_length=30),
        ),
    ]
