export const SIGNUP_PROJECT_REQUEST= "SIGNUP_PROJECT_REQUEST" 
export const SIGNUP_PROJECT_SUCCESS= "SIGNUP_PROJECT_SUCCESS" 
export const SIGNUP_PROJECT_FAIL= "SIGNUP_PROJECT_FAIL" 

export const LOGIN_PROJECT_REQUEST= "LOGIN_PROJECT_REQUEST" 
export const LOGIN_PROJECT_SUCCESS= "LOGIN_PROJECT_SUCCESS" 
export const LOGIN_PROJECT_FAIL= "LOGIN_PROJECT_FAIL"

export const LOGOUT_PROJECT= "LOGOUT_PROJECT"

export const GET_BLOGS_REQUEST= "GET_BLOGS_REQUEST"
export const GET_BLOGS_SUCCESS= "GET_BLOGS_SUCCESS"
export const GET_BLOGS_FAIL= "GET_BLOGS_FAIL"

export const CREATE_BLOG_REQUEST= "CREATE_BLOG_REQUEST"
export const CREATE_BLOG_SUCCESS= "CREATE_BLOG_SUCCESS"
export const CREATE_BLOG_FAIL= "CREATE_BLOG_FAIL"

export const GET_ASSESSMENT_REQUEST="GET_ASSESSMENT_REQUEST"
export const GET_ASSESSMENT_SUCCESS="GET_ASSESSMENT_SUCCESS"
export const GET_ASSESSMENT_FAIL="GET_ASSESSMENT_FAIL"

export const ASSESSMENT_DETAIL_REQUEST='ASSESSMENT_DETAIL_REQUEST'
export const ASSESSMENT_DETAIL_SUCCESS='ASSESSMENT_DETAIL_SUCCESS'
export const ASSESSMENT_DETAIL_FAIL='ASSESSMENT_DETAIL_FAIL'

export const GET_USERDETAIL_REQUEST='GET_USERDETAIL_REQUEST'
export const GET_USERDETAIL_SUCCESS='GET_USERDETAIL_SUCCESS'
export const GET_USERDETAIL_FAIL='GET_USERDETAIL_FAIL'

export const POST_RESPONSE_REQUEST='POST_RESPONSE_REQUEST'
export const POST_RESPONSE_SUCCESS='POST_RESPONSE_SUCCESS'
export const POST_RESPONSE_FAIL='POST_RESPONSE_FAIL'

export const GET_DOCTORS_REQUEST='GET_DOCTORS_REQUEST'
export const GET_DOCTORS_SUCCESS='GET_DOCTORS_SUCCESS'
export const GET_DOCTORS_FAIL='GET_DOCTORS_FAIL'

export const GET_DOCTOR_REQUEST='GET_DOCTOR_REQUEST'
export const GET_DOCTOR_SUCCESS='GET_DOCTOR_SUCCESS'
export const GET_DOCTOR_FAIL='GET_DOCTOR_FAIL'


export const GET_RESPONSE_REQUEST='GET_RESPONSE_REQUEST'
export const GET_RESPONSE_SUCCESS='GET_RESPONSE_SUCCESS'
export const GET_RESPONSE_FAIL='GET_RESPONSE_FAIL'

export const POST_QUERY_REQUEST='POST_QUERY_REQUEST'
export const POST_QUERY_SUCCESS='POST_QUERY_SUCCESS'
export const POST_QUERY_FAIL='POST_QUERY_FAIL'


